### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by sidm11** [dheerajsavanthy/Discord_ChatBot#1]
from tensorflow.python._pywrap_tfe import *
ImportError: /opt/virtualenvs/python3/lib/python3.8/site-packages/tensorflow/python/_pywrap_tfe.so: symbol TFE_ContextOptionsSetMirroringPolicy version tensorflow not defined in file _pywrap_tensorflow_internal.so with link time reference

This happens when I try to run the from 'python RecommenderBot.py' file.

**Comment by dheerajsavanthy** [comment]
Tensorflow isn't involved in the chatbot project. However, you may wanna reinstall tensorflow and try for what you're working on.
